server:
  port: 8084
  servlet:
    session:
      cookie:
        name: WEBSESSION
security:
  oauth2:
    client:
      client-id: gym-home
      client-secret: 0564f7a2-05df-4cf9-bb85-bd4058283553
      access-token-uri: ${common.authorization.accesstokenuri}
      user-authorization-uri: ${common.authorization.userauthorizationuri}
      scope: read, write
      authorized-grant-types: authorization_code
    resource:
      token-info-uri: ${common.authorization.tokeninfouri}
zuul:
  sensitive-headers:
    - Cookie
    - Set-Cookie
  routes:
    angular:
      path: /**
      url: http://localhost:4200
    accounts:
      path: /accounts/**
      serviceId: accounts
eureka:
  client:
    serviceUrl:
      defaultZone: http://${common.eureka.host}:${common.eureka.port}/eureka