server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
security:
  oauth2:
    gym-home:
      access-token-uri: http://localhost:8080/oauth/token
      scope: read
      client-id: authentication
      client-secret: 125a607e-f6ff-4352-ba37-641f081ec904
      id: accounts
logging:
  level:
    root: info
server:
  session:
    cookie:
      name: OAUTH2SESSION
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
