server:
  port: ${common.authorization.port}
  session:
      cookie:
        name: OAUTH2SESSION
spring:
  datasource:
    host: localhost
    url: jdbc:postgresql://${spring.datasource.host}:5432/auth
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  cloud:
    consul:
      enabled: false
      config:
        enabled: false
security:
  oauth2:
    gym-home:
      access-token-uri: ${common.authorization.accessTokenUri}
      scope: read
      client-id: authentication
      client-secret: 125a607e-f6ff-4352-ba37-641f081ec904
      id: accounts
logging:
  level:
    root: info
