server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jpiecuch/config
          search-paths: configs, configs/{application}
security:
  user:
    password: 'mysecret'