server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jpiecuch/config
          search-paths: configs
  security:
    user:
      password: '{noop}mysecret'