server:
  port: ${common.accounts.port}
security:
  oauth2:
    resource:
      token-info-uri: ${common.authorization.tokenInfoUri}
      id: accounts
    client:
      client-id: gym-home
      client-secret: 0564f7a2-05df-4cf9-bb85-bd4058283553
spring:
  datasource:
    host: localhost
    port: 5432
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/accounts
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver