common:
  accounts:
    port: 8082
  eureka:
    host: localhost
    port: 8083
  web:
    port: 8084
  authorization:
    host: localhost
    port: 8085
    baseUrl: http://${common.authorization.host}:${common.authorization.port}
    accessTokenUri: ${common.authorization.baseUrl}/oauth/token
    userAuthorizationUri: ${common.authorization.baseUrl}/oauth/authorize
    tokenInfoUri: ${common.authorization.baseUrl}/oauth/check_token
spring:
  cloud:
    config:
      override-system-properties: false
spring:
  cloud:
    consul:
      host: localhost
      port: 8500