apiVersion: v1
kind: ConfigMap
metadata:
  name: config-filebeat-config
  labels:
    app: config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /app/logs/spring.log
    output.logstash:
      hosts: ["logstash-service:5044"]