apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: jpiecuch/config:latest
        ports:
        - containerPort: 8081
        env:
          - name: LOGGING_LEVEL_ROOT
            value: info