verticles:
  http:
    name: java-guice:pl.jakubpiecuch.exercises.http.HttpVerticle
    options:
      config:
        guice_binder: pl.jakubpiecuch.exercises.http.HttpBinder
        server:
          port: 8086
          host: locahost